---
name: "Tests"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable cache for Nix
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run Nix checks
        run: nix flake check

      - name: Configure the build
        run: cabal configure --enable-nix --enable-tests --enable-benchmarks --disable-documentation

      - name: Install dependencies
        run: nix develop --command cabal --enable-nix build all --only-dependencies

      - name: Build
        run: nix develop --command cabal --enable-nix build all

      - name: Run tests
        run: nix develop --command cabal test all

      # - name: Check cabal file
      #   run: nix develop --command cabal check

      - name: Build documentation
        run: nix develop --command cabal --enable-nix haddock all
