---
name: "Tests"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  checks:
    name: "Run Nix checks"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable cache for Nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Nix checks
        run: nix flake check

  default-ghc:
    name: "Build & test with Nix (default unstable GHC)"
    needs: [checks]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Enable cache for Nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build default package with Nix
        run: nix build

  ghc-versions:
    name: "Build & test with Nix (${{ matrix.ghc }})"
    needs: [checks]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: [ghc96, ghc98, ghc910, ghc912]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Enable cache for Nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package with Nix (${{ matrix.ghc }})
        run: nix build ".#richenv-${{ matrix.ghc }}"

